---
version: "3.8"
services:
  app:
    restart: unless-stopped
    image: python:3.10.13
    # ports:
    #   - "8000:8000"
    volumes:
      - ./api:/app
    command: sh -c "cd /app && rm -rf .git/hooks && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*' "
    depends_on:
      redis:
        condition: service_healthy
  redis:
    restart: unless-stopped
    image: redis/redis-stack
    # ports:
    #   - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --protected-mode no  --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so
    volumes:
      - ./redis-data:/data
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 30s
        timeout: 10s
        retries: 5

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      # - letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
